<?php

/**
 * @file
 * Contains train_neo_2.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\train_neo_2\Event\UserLoginEvent;
/**
 * Implements hook_help().
 */
function train_neo_2_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the train_neo_2 module.
    case 'help.page.train_neo_2':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}



function train_neo_2_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  if($form_id == 'default_form') {
    // kint($form['#form_id']); exit;
  }
  
}

function train_neo_2_theme($existing, $type, $theme, $path) {
  return [
    'custom_block' => [
      'variables' => [
        'content' => [],
        'custom_title' => NULL,
      ],
    ],
  ];
}

function train_neo_2_preprocess_page(&$variables) {
  $data = "testing purpose";
  $variables['custom_data'] = $data;
  // kint($variables);
}



function train_neo_2_user_login($account) {

  $event  = new UserLoginEvent($account);

  $event_dispatcher = \Drupal::service('event_dispatcher');

  $event_dispatcher->dispatch(UserLoginEvent::EVENT_NAME, $event);
  
}







