train_neo_2.default_config_form:
  title: 'DefaultConfigForm'
  route_name: train_neo_2.default_config_form
  description: 'A description for the menu entry'
  parent: system.admin_config_system
  weight: 99